"use strict";
let myString;
let myNum;
let myBool;
let myVar;
/* let strArr: string[];
let numArr: number[];
let boolArr: boolean[]; */
myString = "Hello".slice(0, 3);
myNum = 0xf;
myBool = false;
myVar = true;
let strArr;
let numArr;
let boolArr;
let strNumTuple;
// console.log(myString);
// console.log(myVar);
strArr = ['Hello', 'World'];
numArr = [1, 2, 3];
boolArr = [true, false, true];
strNumTuple = ['Hello', 4];
let myVoid = undefined;
let myNull = null;
// let myUndefined: undefined = null;
// console.log(strArr);
// console.log(numArr);
// console.log(boolArr);
console.log(myVoid);
